<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <RootNamespace>NOBOIShooter</RootNamespace>
    <AssemblyName>NOBOIShooter</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <StartupObject />
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" />
    <EmbeddedResource Include="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NOBOIShooter.Shared\NOBOIShooter.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Condition="'$(BuildContent)' != 'false'" Include="..\NOBOIShooter.Shared\Content\Content.mgcb" />
  </ItemGroup>
</Project>
