<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>NOBOIShooter.Android</RootNamespace>
    <AssemblyName>NOBOIShooter.Android</AssemblyName>
    <ApplicationId>com.noboi.shooter</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.5.1" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NOBOIShooter.Shared\NOBOIShooter.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Condition="'$(BuildContent)' != 'false'" Include="..\NOBOIShooter.Shared\Content\Content.mgcb" />
  </ItemGroup>
</Project>
