<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NOBOIShooter</RootNamespace>
    <AssemblyName>NOBOIShooter.Shared</AssemblyName>
    <NoWarn>SYSLIB0011</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5.1" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>
</Project>
